language: c

dist: trusty

compiler:
  - clang-3.8
  - gcc

script:
    - make clean debug

addons:
  apt:
    sources:
    - sourceline: "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main"
      key_url: http://llvm.org/apt/llvm-snapshot.gpg.key
    packages:
    - clang-3.8
    - dbus
    - libdbus-1-dev
    - expat
    - openssl 
    - curl
    - libev-libevent-dev

