language: c

dist: trusty

compiler:
  - clang-5.0
  - gcc-7

before_script:
    - (sleep 10; pkill mpris-scrobbler) & >/dev/null || true
script:
    - make clean debug

addons:
  apt:
    sources:
    - sourceline: "ppa:ubuntu-toolchain-r/test"
    - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main"
      key_url: http://llvm.org/apt/llvm-snapshot.gpg.key
    packages:
    - gcc-7
    - clang-5.0
    - dbus
    - libdbus-1-dev
    - libexpat1
    - libexpat1-dev
    - openssl
    - curl
    - libevent-dev

